export const ADD_ACTIVITY = 'ACTIVITY::ADD_ACTIVITY';
export const UPDATE_ACTIVITY = 'ACTIVITY::UPDATE_ACTIVITY';
export const DELETE_ACTIVITY = 'ACTIVITY::DELETE_ACTIVITY';

export const UPDATE_DATA_LOG = 'LOG::UPDATE_DATA_LOG';
